/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class com_example_cvlab_opencvfacedetection_OpencvClass */
using namespace cv;
#ifndef _Included_com_example_cvlab_opencvfacedetection_OpencvClass
#define _Included_com_example_cvlab_opencvfacedetection_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cvlab_opencvfacedetection_OpencvClass
 * Method:    facedetection
 * Signature: (J)V
 */
void detect(Mat &frame);
JNIEXPORT void JNICALL Java_com_example_cvlab_opencvfacedetection_OpencvClass_facedetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
