/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
#include <opencv2/opencv.hpp>
#include <opencv2/highgui/highgui.hpp>

#include <dlib/opencv.h>
#include <dlib/image_processing/frontal_face_detector.h>
#include <dlib/image_processing/render_face_detections.h>
#include <dlib/image_processing.h>
#include <dlib/gui_widgets.h>

/* Header for class com_example_cvlab_faciallandmarkdetection_NativeClass */
using namespace cv;
using namespace dlib;
using namespace std;

#ifndef _Included_com_example_cvlab_facelandmarkdetection1_NativeClass
#define _Included_com_example_cvlab_facelandmarkdetection1_NativeClass
#ifdef __cplusplus
extern "C" {
#endif

void faceDetectionDlib(Mat& img, Mat& dst);
void renderToMat(std::vector<full_object_detection>& dets, Mat& dst);
/*
 * Class:     com_example_cvlab_facelandmarkdetection1_NativeClass
 * Method:    getMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_cvlab_facelandmarkdetection1_NativeClass_getMessage
  (JNIEnv *, jclass);

/*
 * Class:     com_example_cvlab_facelandmarkdetection1_NativeClass
 * Method:    LandmarkDetection
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_cvlab_facelandmarkdetection1_NativeClass_LandmarkDetection
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
